version: '3.9'

services:
  mysql:
    build:
      context: ./database
      dockerfile: /Users/rjoella/Desktop/notpad/docker/database/Dockerfile
    ports:
      - '3306:3306'
    restart: always
    networks:
      - go_net
    env_file: ./.env
  app:
    build:
      context: ./app
      dockerfile: /Users/rjoella/Desktop/notpad/docker/app/Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mysql
    restart: always
    networks:
      - go_net
  
networks:
  go_net: