version: '3'
services:
  mysqlserver:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "1111"

  myapp:
    image: notepad
    environment:
      MYSQL_SERVER: "mysqlserver"
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "1111"