version: '3'
services:
  mysqlserver:
    # image: mysql/mysql-server
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "password"

  myapp:
    image: notepad
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile_app
    environment:
      MYSQL_SERVER: "mysqlserver"
      MYSQL_DATABASE: "snippetbox"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "password"
    restart: always
    ports:
      - "8080:4000"