# FROM golang:1.16-alpine as build

# ENV CGO_ENABLED=0
# Create workdir
# WORKDIR /app

# Copy modules files
# COPY ./go.sum .
# COPY ./go.mod .

# COPY . .
#Installation modules
# RUN go mod download

#Copy last part project
# COPY ./cmd .
# COPY ./pkg .
# COPY ./ui .

# Build project bin
# RUN go build -o /test ./cmd/web/
# CMD sleep 10;
# CMD top
# Deploy artifact to small image
# FROM debian:buster
# ENV CGO_ENABLED=0
# WORKDIR /

# COPY --from=build /test /test

FROM golang:latest 
RUN apt -y update && apt -y install git
RUN mkdir /app 
ADD ./app /app/ 
WORKDIR /app 
RUN go build -o main /app/cmd/web
ADD start_app.sh /
RUN chmod +x /start_app.sh
CMD /start_app.sh

